version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
